username: TrainzCoder
quotes:
  - text: "Data is a precious thing and will last longer than the systems themselves."
    author: "Tim Berners-Lee"
    author_detail_url: "https://id.wikipedia.org/wiki/Tim_Berners-Lee"
    created_at: "15 Oktober 2021"
