name: Continuous integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node Modules
      run: npm install
    - name: Run ESLint
      run: npm run lint